#!/usr/bin/env python3
# Copyright 2025 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os

def main():
    parser = argparse.ArgumentParser(description="Embed assets into C++ source.")
    parser.add_argument("--output_h", required=True, help="Output header file")
    parser.add_argument("--output_cc", required=True, help="Output source file")
    parser.add_argument("--namespace", default="mujoco", help="Namespace for the generated code")
    parser.add_argument("--strip", default="", help="Prefix to strip from asset names")
    parser.add_argument("inputs", nargs="+", help="Input files to embed")

    args = parser.parse_args()

    header_content = f"""// Generated by embed_assets.py. DO NOT EDIT.
#ifndef MUJOCO_FILAMENT_ASSETS_EMBED_H_
#define MUJOCO_FILAMENT_ASSETS_EMBED_H_

#include <cstddef>

namespace {args.namespace} {{

struct FileToc {{
  const char* name;
  const unsigned char* data;
  size_t size;
}};

const FileToc* filament_assets_embed_create();
size_t filament_assets_embed_size();

}}  // namespace {args.namespace}

#endif  // MUJOCO_FILAMENT_ASSETS_EMBED_H_
"""

    with open(args.output_h, 'w') as f:
        f.write(header_content)

    cc_content = [
        f'// Generated by embed_assets.py. DO NOT EDIT.',
        f'#include "{os.path.basename(args.output_h)}"',
        '',
        f'namespace {args.namespace} {{',
        ''
    ]

    toc_entries = []
    for i, input_path in enumerate(args.inputs):
        name = input_path
        if args.strip and name.startswith(args.strip):
            name = name[len(args.strip):].lstrip('/')

        var_name = f"asset_data_{i}"
        with open(input_path, 'rb') as f:
            data = f.read()

        cc_content.append(f"static const unsigned char {var_name}[] = {{")
        # Format bytes as hex and join them
        hex_data = ', '.join(f'0x{b:02x}' for b in data)
        cc_content.append(f"  {hex_data}")
        cc_content.append("};")
        cc_content.append("")

        toc_entries.append(f'  {{"{name}", {var_name}, {len(data)}}}')

    cc_content.append("static const FileToc toc[] = {")
    cc_content.append(',\n'.join(toc_entries))
    cc_content.append("};")
    cc_content.append("")
    cc_content.append(f"const FileToc* filament_assets_embed_create() {{ return toc; }}")
    cc_content.append(f"size_t filament_assets_embed_size() {{ return sizeof(toc) / sizeof(toc[0]); }}")
    cc_content.append("")
    cc_content.append(f"}}  // namespace {args.namespace}")

    with open(args.output_cc, 'w') as f:
        f.write('\n'.join(cc_content))

if __name__ == "__main__":
    main()
