if(EXISTS "/home/matias/personal/mujoco/build2/test/user/user_api_test[1]_tests.cmake")
  include("/home/matias/personal/mujoco/build2/test/user/user_api_test[1]_tests.cmake")
else()
  add_test(user_api_test_NOT_BUILT user_api_test_NOT_BUILT)
endif()
