if(EXISTS "/home/matias/personal/mujoco/build2/test/engine/engine_solver_test[1]_tests.cmake")
  include("/home/matias/personal/mujoco/build2/test/engine/engine_solver_test[1]_tests.cmake")
else()
  add_test(engine_solver_test_NOT_BUILT engine_solver_test_NOT_BUILT)
endif()
