# CMake generated Testfile for 
# Source directory: /home/matias/personal/mujoco/python/mujoco/util
# Build directory: /home/matias/personal/mujoco/build2/python/mujoco/util
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ArrayTraitsTest.CArrayType "/home/matias/personal/mujoco/build2/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.CArrayType")
set_tests_properties(ArrayTraitsTest.CArrayType PROPERTIES  DEF_SOURCE_LINE "array_traits_test.cc:27" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayNdim "/home/matias/personal/mujoco/build2/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayNdim")
set_tests_properties(ArrayTraitsTest.ArrayNdim PROPERTIES  DEF_SOURCE_LINE "array_traits_test.cc:39" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayScalarType "/home/matias/personal/mujoco/build2/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayScalarType")
set_tests_properties(ArrayTraitsTest.ArrayScalarType PROPERTIES  DEF_SOURCE_LINE "array_traits_test.cc:47" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.MakeEigen "/home/matias/personal/mujoco/build2/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.MakeEigen")
set_tests_properties(ArrayTraitsTest.MakeEigen PROPERTIES  DEF_SOURCE_LINE "array_traits_test.cc:67" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.IsCallable "/home/matias/personal/mujoco/build2/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.IsCallable")
set_tests_properties(FuncTraitsTest.IsCallable PROPERTIES  DEF_SOURCE_LINE "func_traits_test.cc:26" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgType "/home/matias/personal/mujoco/build2/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgType")
set_tests_properties(FuncTraitsTest.FuncArgType PROPERTIES  DEF_SOURCE_LINE "func_traits_test.cc:55" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgCount "/home/matias/personal/mujoco/build2/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgCount")
set_tests_properties(FuncTraitsTest.FuncArgCount PROPERTIES  DEF_SOURCE_LINE "func_traits_test.cc:141" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.UnwrapArgs "/home/matias/personal/mujoco/build2/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.UnwrapArgs")
set_tests_properties(FuncWrapTest.UnwrapArgs PROPERTIES  DEF_SOURCE_LINE "func_wrap_test.cc:74" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.ReturnArrayArg0 "/home/matias/personal/mujoco/build2/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.ReturnArrayArg0")
set_tests_properties(FuncWrapTest.ReturnArrayArg0 PROPERTIES  DEF_SOURCE_LINE "func_wrap_test.cc:96" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(TupleToolsTest.Slice "/home/matias/personal/mujoco/build2/bin/tuple_tools_test" "--gtest_filter=TupleToolsTest.Slice")
set_tests_properties(TupleToolsTest.Slice PROPERTIES  DEF_SOURCE_LINE "tuple_tools_test.cc:25" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;2;add_test;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake:510:EVAL;0;;/usr/local/share/cmake-3.31/Modules/GoogleTest.cmake;510;cmake_language;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;96;gtest_add_tests;/home/matias/personal/mujoco/python/mujoco/util/CMakeLists.txt;0;")
