if(EXISTS "/home/matias/personal/mujoco/build2/test/xml/xml_utils_test[1]_tests.cmake")
  include("/home/matias/personal/mujoco/build2/test/xml/xml_utils_test[1]_tests.cmake")
else()
  add_test(xml_utils_test_NOT_BUILT xml_utils_test_NOT_BUILT)
endif()
